//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public long Id { get; set; }
        public long Cliente_Id { get; set; }
        public long Tatuador_Id { get; set; }
        public System.DateTimeOffset Data_Sessao { get; set; }
        public Nullable<System.TimeSpan> Duracao { get; set; }
        public string Status { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Tatuadores Tatuadores { get; set; }
    }
}
