//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public long Id { get; set; }
        public long Cliente_Id { get; set; }
        public long Tatuagem_Id { get; set; }
        public System.DateTimeOffset DataCompra { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Tatuagens Tatuagens { get; set; }
    }
}
