//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Tatuadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tatuadores()
        {
            this.Agenda = new HashSet<Agenda>();
            this.Tatuagens = new HashSet<Tatuagens>();
        }
    
        public long Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public string Telefone { get; set; }
        public string Especialidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agenda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tatuagens> Tatuagens { get; set; }

        public void cadastrarTatuadores(Tatuadores tatuador)
        {
            using (SiriusTattooEntities ctx = new SiriusTattooEntities())
            {
                ctx.Tatuadores.Add(tatuador);
                ctx.SaveChanges();
            }
        }
        public Tatuadores consultarTatuadoresPorEmail(string email)
        {
            using (SiriusTattooEntities ctx = new SiriusTattooEntities())
            {
                return ctx.Tatuadores.FirstOrDefault(t => t.Email == email);
            }
        }
 
    }
}
